### ISSUE TITLE
Details on the weighting matrix

### ISSUE THREAD

**Issue by Kylin9511** [ZhiwenShao/MCNet-Extension#1]
In both paper, we can find accurate description of the weights matrix W as follows.
<div align=center><img width="150" height="67" src="https://user-images.githubusercontent.com/25010679/45138407-db020980-b1de-11e8-9bde-10daaaa5e975.png"/></div>
<div align=center><img width="500" height="84" src="https://user-images.githubusercontent.com/25010679/45138542-5d8ac900-b1df-11e8-930c-0de98f1311fe.png"/></div>

So here comes my question: The weight matrix is actually a fully connected layer. Is it true that in this work the FC layer is not updated through back-propagation? Or the __W__ here only refer to a weighting params for the FC layer, the back-propagation process still exist?

If the back-propagation still exist, little refinement for the description in the thesis is recommended to reduce ambiguity.

**Comment by ZhiwenShao** [comment]
The weight in the formulation is for the loss of the corresponding landmark. Here w_j is not the element of weight matrix W of the fully-connected layer.

**Comment by Kylin9511** [comment]
Oh, in that case the situation is clear. However, why do you use the same letter "W"? It is a little bit confusing at the first glance.

**Comment by ZhiwenShao** [comment]
OK, a different notation is better. Thanks for your suggestions.
